name: Assign Reviewers

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Assign reviewers using auto-assign action
        uses: kentaro-m/auto-assign-reviewer@v1.3.0
        with:
          reviewers: '1Nexus0'
          numberOfReviewers: 1
